FROM hyperdyne/simulator:swmm
COPY . .
# put the engine version number to use, note: linux only supports 5.1.014 at this time
ENV VERSION="5.1.014"
# put the name of your input file here without the .inp extension
ENV SWMMFILE=Example9