#The line below determines the build image to use

FROM hyperdyne/simulator:srh2d

#The line below determines the location to copy from and the location to copy to 

COPY . C:\\Users\\Public\\srh2d

ENV SRH2D_MODEL=case