FROM hyperdyne/simulator:tuflow
COPY . .

## This is the name of the subdirectory container your .bat file
ENV RUN_DIR runs

## This is the name of the .bat file that performs the Tuflow simulations.
## NOTE: the environement variable EXE_iSP and EXE_iDP are already configured for you
ENV TUFLOW_BAT '_ run all simulations.bat'